version: '3'
services:
  registry:
    restart: always
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"  
    volumes:
      - /docker/registry/data:/var/lib/registry
  broker:
    restart: always
    container_name: broker
    build: 
      context: ./broker
    environment:
      - ZMQ_BIND_ADDRESS=tcp://*:5554
      - REDIS_ADDRESS=redis://redis:6379
    ports:
      - "5554:5554"
    networks:
      - redis-net
    depends_on:
      - redis
  api:
    restart: always
    container_name: api    
    networks:
      - redis-net
    build: 
      context: ./api
    environment:
      - ZMQ_BROKER_ADDRESS=tcp://broker:5554
      - BrokerIP=192.168.1.180
    ports:
      - "3000:3000"
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock
      - uploads:/usr/src/app/dist/uploads/
    depends_on:
      - registry
      - broker
  redis:
    restart: always
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
  uploads:
    
        
        